apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-devops-cron
spec:
  schedule: "*/1 * * * *"   # Runs every 1 minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args: ["/bin/sh","-c","echo 'Hello DevOps from Kubernetes CronJob!'"]
          restartPolicy: OnFailure
